# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_lmb_bram_0/microSense_top_level_lmb_bram_0.xci
# IP: The module: 'microSense_top_level_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_lmb_bram_0/microSense_top_level_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microSense_top_level_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_lmb_bram_0/microSense_top_level_lmb_bram_0.xci
# IP: The module: 'microSense_top_level_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_lmb_bram_0/microSense_top_level_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microSense_top_level_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
