# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/microSense_top_level/microSense_top_level.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level || ORIG_REF_NAME==microSense_top_level} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_clk_wiz_0_0/microSense_top_level_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_clk_wiz_0_0 || ORIG_REF_NAME==microSense_top_level_clk_wiz_0_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_axi_uartlite_0_0/microSense_top_level_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_axi_uartlite_0_0 || ORIG_REF_NAME==microSense_top_level_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_axi_gpio_0_0/microSense_top_level_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_axi_gpio_0_0 || ORIG_REF_NAME==microSense_top_level_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_axi_gpio_1_0/microSense_top_level_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_axi_gpio_1_0 || ORIG_REF_NAME==microSense_top_level_axi_gpio_1_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_axi_gpio_2_0/microSense_top_level_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_axi_gpio_2_0 || ORIG_REF_NAME==microSense_top_level_axi_gpio_2_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_vga_module_0_0/microSense_top_level_vga_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_vga_module_0_0 || ORIG_REF_NAME==microSense_top_level_vga_module_0_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_microblaze_0_0/microSense_top_level_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_microblaze_0_0 || ORIG_REF_NAME==microSense_top_level_microblaze_0_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_mdm_1_0/microSense_top_level_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_mdm_1_0 || ORIG_REF_NAME==microSense_top_level_mdm_1_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_rst_clk_wiz_0_100M_0/microSense_top_level_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==microSense_top_level_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_microblaze_0_axi_periph_0/microSense_top_level_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microSense_top_level_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_xbar_0/microSense_top_level_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_xbar_0 || ORIG_REF_NAME==microSense_top_level_xbar_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_dlmb_v10_0/microSense_top_level_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_dlmb_v10_0 || ORIG_REF_NAME==microSense_top_level_dlmb_v10_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_ilmb_v10_0/microSense_top_level_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_ilmb_v10_0 || ORIG_REF_NAME==microSense_top_level_ilmb_v10_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_dlmb_bram_if_cntlr_0/microSense_top_level_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microSense_top_level_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_ilmb_bram_if_cntlr_0/microSense_top_level_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microSense_top_level_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_lmb_bram_0/microSense_top_level_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_lmb_bram_0 || ORIG_REF_NAME==microSense_top_level_lmb_bram_0} -quiet] -quiet

# IP: bd/microSense_top_level/ip/microSense_top_level_top_level_SAR_0_0/microSense_top_level_top_level_SAR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microSense_top_level_top_level_SAR_0_0 || ORIG_REF_NAME==microSense_top_level_top_level_SAR_0_0} -quiet] -quiet

# XDC: bd/microSense_top_level/microSense_top_level_ooc.xdc
