# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.cache/wt [current_project]
set_property parent.project_path C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/Aklas/Desktop/microSense_topLevel/vga
  c:/Users/Aklas/Desktop/microSense_topLevel/sar
} [current_project]
set_property ip_output_repo c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/hdl/microSense_top_level_wrapper.vhd
add_files C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/microSense_top_level.bd
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_clk_wiz_0_0/microSense_top_level_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_clk_wiz_0_0/microSense_top_level_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_clk_wiz_0_0/microSense_top_level_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_uartlite_0_0/microSense_top_level_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_uartlite_0_0/microSense_top_level_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_uartlite_0_0/microSense_top_level_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_0_0/microSense_top_level_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_0_0/microSense_top_level_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_0_0/microSense_top_level_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_1_0/microSense_top_level_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_1_0/microSense_top_level_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_1_0/microSense_top_level_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_2_0/microSense_top_level_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_2_0/microSense_top_level_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_axi_gpio_2_0/microSense_top_level_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_microblaze_0_0/microSense_top_level_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_microblaze_0_0/microSense_top_level_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_microblaze_0_0/microSense_top_level_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_mdm_1_0/microSense_top_level_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_mdm_1_0/microSense_top_level_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_rst_clk_wiz_0_100M_0/microSense_top_level_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_rst_clk_wiz_0_100M_0/microSense_top_level_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_rst_clk_wiz_0_100M_0/microSense_top_level_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_xbar_0/microSense_top_level_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_dlmb_v10_0/microSense_top_level_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_dlmb_v10_0/microSense_top_level_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_ilmb_v10_0/microSense_top_level_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_ilmb_v10_0/microSense_top_level_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_dlmb_bram_if_cntlr_0/microSense_top_level_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_ilmb_bram_if_cntlr_0/microSense_top_level_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/ip/microSense_top_level_lmb_bram_0/microSense_top_level_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/sources_1/bd/microSense_top_level/microSense_top_level_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/Aklas/Desktop/microSense_topLevel/microSense/microSense.srcs/constrs_1/new/constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top microSense_top_level_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microSense_top_level_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file microSense_top_level_wrapper_utilization_synth.rpt -pb microSense_top_level_wrapper_utilization_synth.pb"
